function thermal = import_thermal(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FLIGHT1THERMALNO331CW2 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  FLIGHT1THERMALNO331CW2 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  flight1thermalno331CW2 = importfile("C:\Users\Pedro\Documents\Faculdade\Bachelorarbeit\Hardt data\flight_1_thermal-no_3_3,1,CW2.csv", [17, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Aug-2024 13:37:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [17, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["datetime", "w_selection", "dist_abs_selection", "dist_rel_selection", "temp_p_diff_selection_cmh", "temp_vp_diff_selection_cmh", "spec_hum_diff_selection_cmh", "temp_p_diff_selection_sht", "temp_vp_diff_selection_sht", "spec_hum_diff_selection_sht", "temp_p_diff_selection_hyt", "temp_vp_diff_selection_hyt", "spec_hum_diff_selection_hyt"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS", "DatetimeFormat", "preserveinput");

% Import the data
thermal = readtable(filename, opts);

end