function stations = import_station_list(filename, startRow, endRow)
% This function imports the station list from the station-list.txt file.
% It is not called by any other function, and should be used whenever the list
% of existing IGRA stations needs to be imported. You should download the file
% from the IGRA website and place it in the IGRA-Parser folder. The function
% was generated by MATLAB and some adjustments were made to clean the data.
% 
% IMPORTFILE Import numeric data from a text file as a matrix.
%   IGRA2STATIONLIST = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   IGRA2STATIONLIST = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   igra2stationlist = importfile('igra2-station-list.txt', 1, 2879);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2024/09/02 23:52:36

%% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column6: categorical (%C)
%	column7: text (%s)
%   column9: double (%f)
%	column11: double (%f)
%   column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%11s%9f%10f%7f%4C%30s%5f%5f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});
dataArray{6} = strtrim(dataArray{6});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
stations = table(dataArray{1:end-1}, 'VariableNames', {'ID','lat','lon','elevation','state','name','firstYear','lastYear','numObs'});

%% Remove mobile stations (lat <= -90 or lat >= 90)
stations = stations(stations.lat >= -90 & stations.lat <= 90, :);
    
end


