function data = sounding_to_table(filename, startRow, endRow)
% Usage: data = sounding_to_table('GMM00010868-data.txt',3,78);
% This function extracts the atmospheric sounding measurements in rows
% startRow to endRow of the file 'filename'. WARNING: this function should
% not be used to attempt to parse header lines. It can only parse lines
% containing actual measument data. The function was generated by MATLAB
% and some adjustments were made to clean the data.

% Auto-generated by MATLAB on 2024/07/03 19:11:05

%% Check usage.
if nargin<=2
    error('You are missing arguments. Check the correct usage\n');
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: categorical (%C)
%	column6: double (%f)
%   column7: categorical (%C)
%	column8: double (%f)
%   column9: categorical (%C)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%1f%1f%6f%7f%1C%5f%1C%5f%1C%5f%6f%6f%6f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Create output variable
% Variable names are according to the IGRA v2.2 specification
data = table(dataArray{1:end-1}, 'VariableNames', {'LVLTYP1','LVLTYP2','ETIME','PRESS','PFLAG','GPH','ZFLAG','TEMP','TFLAG','RH','DPDP','WDIR','WSPD'});
%% Replace missing values with NaN
data = standardizeMissing(data,{-9999,-8888});

